# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=400)),
                ('field_value', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='GenericCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('last_modified_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('genericcollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AddressBookApp.GenericCollection')),
            ],
            bases=('AddressBookApp.genericcollection',),
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('genericcollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AddressBookApp.GenericCollection')),
                ('member_of_book', models.ManyToManyField(to='AddressBookApp.AddressBook')),
            ],
            bases=('AddressBookApp.genericcollection',),
        ),
        migrations.AddField(
            model_name='contactfield',
            name='member_of_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddressBookApp.ContactCard'),
        ),
    ]
